[colors.primary]
background = "#f7f3f7"
foreground = "#695d69"
dim_foreground = "#9e8f9e"
bright_foreground = "#1b181b"

[colors.cursor]
text = "#f7f3f7"
cursor = "#695d69"

[colors.vi_mode_cursor]
text = "#f7f3f7"
cursor = "#695d69"

[colors.search.matches]
foreground = "#f7f3f7"
background = "#516aec"

[colors.search.focused_match]
foreground = "#f7f3f7"
background = "#bb8a35"

[colors.footer_bar]
foreground = "#695d69"
background = "#f7f3f7"

[colors.hints.start]
foreground = "#f7f3f7"
background = "#bb8a35"

[colors.hints.end]
foreground = "#695d69"
background = "#f7f3f7"

[colors.selection]
text = "#695d69"
background = "#9e8f9e"

[colors.normal]
black = "#f7f3f7"
red = "#ca402b"
green = "#918b3b"
yellow = "#bb8a35"
blue = "#516aec"
magenta = "#7b59c0"
cyan = "#159393"
white = "#695d69"

[colors.bright]
black = "#9e8f9e"
red = "#ca402b"
green = "#918b3b"
yellow = "#bb8a35"
blue = "#516aec"
magenta = "#7b59c0"
cyan = "#159393"
white = "#1b181b"

[colors.dim]
black = "#9e8f9e"
red = "#ca402b"
green = "#918b3b"
yellow = "#bb8a35"
blue = "#516aec"
magenta = "#7b59c0"
cyan = "#159393"
white = "#1b181b"

[[colors.indexed_colors]]
index = 16
color = "#bb8a35"

[[colors.indexed_colors]]
index = 17
color = "#ca402b"
