[colors.primary]
background = "#fbf1c7"
foreground = "#3c3836"
dim_foreground = "#665c54"
bright_foreground = "#282828"

[colors.cursor]
text = "#fbf1c7"
cursor = "#3c3836"

[colors.vi_mode_cursor]
text = "#fbf1c7"
cursor = "#3c3836"

[colors.search.matches]
foreground = "#fbf1c7"
background = "#458588"

[colors.search.focused_match]
foreground = "#fbf1c7"
background = "#d65d0e"

[colors.footer_bar]
foreground = "#3c3836"
background = "#f2e5bc"

[colors.hints.start]
foreground = "#fbf1c7"
background = "#d79921"

[colors.hints.end]
foreground = "#3c3836"
background = "#f2e5bc"

[colors.selection]
text = "#3c3836"
background = "#ebdbb2"

[colors.normal]
black = "#3c3836"
red = "#cc241d"
green = "#98971a"
yellow = "#d79921"
blue = "#458588"
magenta = "#b16286"
cyan = "#689d6a"
white = "#fbf1c7"

[colors.bright]
black = "#7c6f64"
red = "#9d0006"
green = "#79740e"
yellow = "#b57614"
blue = "#076678"
magenta = "#8f3f71"
cyan = "#427b58"
white = "#f9f5d7"

[colors.dim]
black = "#7c6f64"
red = "#cc241d"
green = "#98971a"
yellow = "#d79921"
blue = "#458588"
magenta = "#b16286"
cyan = "#689d6a"
white = "#f9f5d7"

[[colors.indexed_colors]]
index = 16
color = "#d65d0e"

[[colors.indexed_colors]]
index = 17
color = "#cc241d"
