#!/usr/bin/env python3
"""Convert Seth's Obsidian Markdown vault into an Org-roam output tree."""

from __future__ import annotations

import argparse
import os
import re
import shutil
import uuid
from dataclasses import dataclass
from pathlib import Path


NAMESPACE = uuid.uuid5(uuid.NAMESPACE_URL, "seth-vault-org-conversion-v1")
CONVERSION_MARKER = ".org-conversion-output"
CONVERSION_MARKER_TEXT = "generated by scripts/convert-vault-to-org.py\n"
DEFAULT_VAULT = Path("/home/seth/vault")
DEFAULT_OUTPUT = Path("/home/seth/org-converted")
CHECKBOX_TODOS = {
    " ": "TODO",
    "x": "DONE",
    "X": "DONE",
    "!": "IMPORTANT",
    "?": "NEEDS_ATTENTION",
    ">": "CURRENTLY_WORKING",
    "~": "ABANDONED",
}


@dataclass(frozen=True)
class Note:
    source: Path
    relative: Path
    target: Path
    title: str
    org_id: str
    frontmatter: dict[str, object]
    body: str
    malformed_frontmatter: bool
    references: dict[str, str]


@dataclass(frozen=True)
class LinkIssue:
    note: Note
    line_number: int
    text: str
    reason: str


@dataclass(frozen=True)
class ConversionWarning:
    note: Note
    reason: str


@dataclass(frozen=True)
class LedgerEntry:
    source: Path
    target: Path
    title: str
    org_id: str
    aliases: list[str]


def slugify(value: str) -> str:
    value = value.strip().lower()
    value = re.sub(r"[^a-z0-9]+", "_", value)
    value = re.sub(r"_+", "_", value).strip("_")
    return value or "untitled"


def lookup_key(value: str) -> str:
    return slugify(value).lower()


def parse_frontmatter(text: str) -> tuple[dict[str, object], str, bool]:
    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        return {}, text, False

    end = next((index for index in range(1, len(lines)) if lines[index].strip() == "---"), None)
    if end is None:
        return {}, text, True

    data: dict[str, object] = {}
    current_key: str | None = None
    for raw_line in lines[1:end]:
        line = raw_line.rstrip()
        list_item = re.match(r"^\s+-\s*(.*)$", line)
        if list_item and current_key:
            data.setdefault(current_key, [])
            if isinstance(data[current_key], list):
                data[current_key].append(list_item.group(1).strip().strip('"'))
            continue

        match = re.match(r"^([A-Za-z0-9_-]+):\s*(.*)$", line)
        if not match:
            continue

        current_key = match.group(1)
        value = match.group(2).strip()
        if value == "[]":
            data[current_key] = []
        elif value.startswith("[") and value.endswith("]"):
            data[current_key] = [item.strip().strip('"') for item in value[1:-1].split(",") if item.strip()]
        elif value == "":
            data[current_key] = []
        else:
            data[current_key] = value.strip('"')

    return data, "\n".join(lines[end + 1 :]), False


def first_heading(markdown: str) -> str | None:
    for line in markdown.splitlines():
        match = re.match(r"^#\s+(.+?)\s*$", line)
        if match:
            return match.group(1).strip()
    return None


def normalize_tag(value: str) -> str:
    return re.sub(r"[^A-Za-z0-9_@#%]+", "_", value.strip().lstrip("#")).strip("_")


def split_wikilink_spans(line: str) -> list[tuple[int, int]]:
    return [match.span() for match in re.finditer(r"!\[\[[^\]]+\]\]|\[\[[^\]]+\]\]", line)]


def in_spans(index: int, spans: list[tuple[int, int]]) -> bool:
    return any(start <= index < end for start, end in spans)


def inline_tags_outside_links(line: str) -> list[str]:
    spans = split_wikilink_spans(line)
    tags: list[str] = []
    for match in re.finditer(r"(?<![\w/#])#([A-Za-z][A-Za-z0-9_/-]*)", line):
        if not in_spans(match.start(), spans):
            tags.append(match.group(1))
    return tags


def strip_inline_tags(line: str) -> str:
    spans = split_wikilink_spans(line)
    result: list[str] = []
    cursor = 0
    for match in re.finditer(r"(?<![\w/#])#[A-Za-z][A-Za-z0-9_/-]*", line):
        if in_spans(match.start(), spans):
            continue
        result.append(line[cursor : match.start()])
        cursor = match.end()
    result.append(line[cursor:])
    return "".join(result).strip()


def clean_heading_title(title: str) -> str:
    title = re.sub(r"\s+:[A-Za-z0-9_:@#%]+:$", "", title).strip()
    title = strip_inline_tags(title)
    return re.sub(r"\s+", " ", title)


def parse_list(value: object) -> list[str]:
    if isinstance(value, list):
        return [str(item) for item in value if str(item).strip()]
    if isinstance(value, str) and value.strip():
        return [value.strip()]
    return []


def org_filetags(tags: list[str]) -> str | None:
    normalized = [normalize_tag(tag) for tag in tags]
    normalized = [tag for tag in normalized if tag]
    if not normalized:
        return None
    return "#+filetags: :" + ":".join(normalized) + ":"


def note_title(path: Path, frontmatter: dict[str, object], body: str) -> str:
    raw_id = frontmatter.get("id")
    if isinstance(raw_id, str) and raw_id.strip():
        return raw_id.strip()
    return first_heading(body) or path.stem


def normalize_reference_label(label: str) -> str:
    return re.sub(r"\s+", " ", label.strip()).lower()


def parse_reference_links(body: str) -> dict[str, str]:
    references: dict[str, str] = {}
    for line in body.splitlines():
        match = re.match(r"^\[([^\]]+)\]:\s+(<[^>]+>|\S+)(?:\s+(?:\"[^\"]*\"|'[^']*'|\([^)]*\)))?\s*$", line)
        if match:
            references[normalize_reference_label(match.group(1))] = markdown_link_target(match.group(2))
    return references


def collect_notes(vault: Path, output: Path) -> list[Note]:
    notes: list[Note] = []
    used_targets: set[Path] = set()

    for source in sorted(vault.rglob("*.md")):
        if any(part.startswith(".") for part in source.relative_to(vault).parts):
            continue

        relative = source.relative_to(vault)
        text = source.read_text(encoding="utf-8")
        frontmatter, body, malformed_frontmatter = parse_frontmatter(text)
        title = note_title(source, frontmatter, body)
        org_id = str(uuid.uuid5(NAMESPACE, relative.as_posix()))
        filename = f"{org_id}-{slugify(title)}.org"

        if relative.parts[0] == "Dailies":
            target_relative = Path("daily") / f"{org_id}-{source.stem}.org"
        else:
            target_relative = Path(filename)

        while target_relative in used_targets:
            target_relative = target_relative.with_stem(f"{target_relative.stem}_{org_id[:8]}")

        used_targets.add(target_relative)
        references = parse_reference_links(body)
        notes.append(Note(source, relative, output / target_relative, title, org_id, frontmatter, body, malformed_frontmatter, references))

    return notes


def note_ledger_entry(note: Note, output: Path) -> LedgerEntry:
    return LedgerEntry(
        note.relative,
        note.target.relative_to(output),
        note.title,
        note.org_id,
        parse_list(note.frontmatter.get("aliases", [])),
    )


def build_lookup_entries(entries: list[LedgerEntry]) -> tuple[dict[str, LedgerEntry | None], dict[str, list[LedgerEntry]]]:
    lookup: dict[str, LedgerEntry | None] = {}
    ambiguous: dict[str, None] = {}
    collisions: dict[str, list[LedgerEntry]] = {}
    for entry in entries:
        keys = {
            entry.source.with_suffix("").as_posix(),
            entry.source.stem,
            entry.title,
            lookup_key(entry.source.with_suffix("").as_posix()),
            lookup_key(entry.source.stem),
            lookup_key(entry.title),
        }
        for alias in entry.aliases:
            keys.add(alias)
            keys.add(lookup_key(alias))
        for key in keys:
            normalized_key = key.lower()
            if normalized_key in ambiguous:
                collisions.setdefault(normalized_key, [])
                if entry not in collisions[normalized_key]:
                    collisions[normalized_key].append(entry)
                continue
            if normalized_key in lookup and lookup[normalized_key] != entry:
                existing = lookup[normalized_key]
                if existing:
                    collisions[normalized_key] = [existing, entry]
                ambiguous[normalized_key] = None
                lookup.pop(normalized_key, None)
                continue
            lookup[normalized_key] = entry
    return lookup, collisions


def build_lookup(notes: list[Note], output: Path) -> tuple[dict[str, LedgerEntry | None], dict[str, list[LedgerEntry]]]:
    return build_lookup_entries([note_ledger_entry(note, output) for note in notes])


def split_wikilink(value: str) -> tuple[str, str | None, str | None]:
    target, alias = (value.split("|", 1) + [None])[:2]
    note, heading = (target.split("#", 1) + [None])[:2]
    return note.strip(), heading.strip() if heading else None, alias.strip() if alias else None


def heading_custom_id(source: Path, heading: str) -> str:
    return "h-" + str(uuid.uuid5(NAMESPACE, f"{source.as_posix()}#{heading}"))[:8]


def build_heading_index(notes: list[Note]) -> dict[Path, set[str]]:
    headings: dict[Path, set[str]] = {}
    for note in notes:
        note_headings: set[str] = set()
        for line in note.body.splitlines():
            heading = re.match(r"^(#{1,6})\s+(.+?)\s*$", line)
            if heading:
                note_headings.add(clean_heading_title(heading.group(2)))
        headings[note.relative] = note_headings
    return headings


def targeted_heading_index(
    notes: list[Note],
    lookup: dict[str, LedgerEntry | None],
    headings: dict[Path, set[str]],
) -> dict[Path, set[str]]:
    targets: dict[Path, set[str]] = {note.relative: set() for note in notes}
    for note in notes:
        in_src = False
        for line in note.body.splitlines():
            fence = re.match(r"^(```|~~~)", line)
            if fence:
                in_src = not in_src
                continue
            if in_src:
                continue
            for match in re.finditer(r"(?<!!)\[\[([^\]]+)\]\]", line):
                note_name, heading, _ = split_wikilink(match.group(1))
                if not heading:
                    continue
                clean_heading = clean_heading_title(heading)
                if not note_name and clean_heading in headings.get(note.relative, set()):
                    targets[note.relative].add(clean_heading)
                    continue
                target = lookup.get(note_name.lower()) or lookup.get(lookup_key(note_name))
                if target and clean_heading in headings.get(target.source, set()):
                    targets[target.source].add(clean_heading)
                    continue
                if note_name.lower() == note.title.lower() and clean_heading in headings.get(note.relative, set()):
                    targets[note.relative].add(clean_heading)
    return targets


def convert_wikilinks(line: str, lookup: dict[str, LedgerEntry | None], headings: dict[Path, set[str]], current: Note, output: Path) -> str:
    def replace_embed(match: re.Match[str]) -> str:
        return match.group(0)

    def replace_link(match: re.Match[str]) -> str:
        note_name, heading, alias = split_wikilink(match.group(1))
        label = alias or heading or note_name
        clean_heading = clean_heading_title(heading) if heading else None
        if heading and not note_name:
            if clean_heading not in headings.get(current.relative, set()):
                return f"[[{match.group(1)}]]"
            return f"[[#{heading_custom_id(current.relative, clean_heading)}][{label}]]"

        target = lookup.get(note_name.lower()) or lookup.get(lookup_key(note_name))
        if target and heading:
            if clean_heading not in headings.get(target.source, set()):
                return f"[[{match.group(1)}]]"
            custom_id = heading_custom_id(target.source, clean_heading)
            if target.source == current.relative:
                return f"[[#{custom_id}][{label}]]"
            target_path = Path(os.path.relpath(output / target.target, current.target.parent)).as_posix()
            return f"[[file:{target_path}::#{custom_id}][{label}]]"
        if target:
            return f"[[id:{target.org_id}][{label}]]"
        if heading and note_name.lower() == current.title.lower() and clean_heading in headings.get(current.relative, set()):
            return f"[[#{heading_custom_id(current.relative, clean_heading)}][{label}]]"
        return f"[[{match.group(1)}]]"

    line = re.sub(r"!\[\[[^\]]+\]\]", replace_embed, line)
    return re.sub(r"(?<!!)\[\[([^\]]+)\]\]", replace_link, line)


def convert_inline_tags(line: str) -> str:
    if line.startswith("#+"):
        return line
    tags = inline_tags_outside_links(line)
    if not tags:
        return line
    normalized = [normalize_tag(tag) for tag in tags]
    stripped = strip_inline_tags(line).rstrip()
    return f"{stripped} :{':'.join(tag for tag in normalized if tag)}:"


def protect_spans(line: str, pattern: str) -> tuple[str, list[str]]:
    replacements: list[str] = []

    def replace(match: re.Match[str]) -> str:
        replacements.append(match.group(0))
        return f"\0{len(replacements) - 1}\0"

    return re.sub(pattern, replace, line), replacements


def restore_spans(line: str, replacements: list[str]) -> str:
    for index, value in enumerate(replacements):
        line = line.replace(f"\0{index}\0", value)
    return line


def protect_converted_spans(line: str, pattern: str, replacements: list[str], template: str) -> str:
    def replace(match: re.Match[str]) -> str:
        value = template
        for index, group in enumerate(match.groups(), 1):
            value = value.replace(f"\\{index}", group)
        replacements.append(value)
        return f"\0{len(replacements) - 1}\0"

    return re.sub(pattern, replace, line)


def convert_inline_code(line: str) -> str:
    return re.sub(r"`{1,2}([^`\n]+)`{1,2}", r"~\1~", line)


def markdown_link_target(destination: str) -> str:
    destination = destination.strip()
    if destination.startswith("<") and destination.endswith(">"):
        destination = destination[1:-1]
    titled_link = re.match(r"^(\S+)\s+(?:\"[^\"]*\"|'[^']*'|\([^)]*\))$", destination)
    if titled_link:
        destination = titled_link.group(1)
    if destination.startswith("<") and destination.endswith(">"):
        destination = destination[1:-1]
    return destination.replace(" ", "%20")


def convert_inline_markdown_links(line: str) -> str:
    result: list[str] = []
    index = 0
    while index < len(line):
        if line[index] == "!" and line[index + 1 : index + 2] == "[":
            result.append(line[index])
            index += 1
            continue
        if line[index] != "[":
            result.append(line[index])
            index += 1
            continue

        label_cursor = index + 1
        label_depth = 1
        while label_cursor < len(line):
            if line[label_cursor] == "[":
                label_depth += 1
            elif line[label_cursor] == "]":
                label_depth -= 1
                if label_depth == 0:
                    break
            label_cursor += 1

        if label_depth != 0 or line[label_cursor + 1 : label_cursor + 2] != "(":
            result.append(line[index])
            index += 1
            continue

        cursor = label_cursor + 2
        depth = 1
        destination: list[str] = []
        while cursor < len(line):
            char = line[cursor]
            if char == "\\" and cursor + 1 < len(line):
                destination.append(line[cursor + 1])
                cursor += 2
                continue
            if char == "(":
                depth += 1
            elif char == ")":
                depth -= 1
                if depth == 0:
                    break
            destination.append(char)
            cursor += 1

        if depth != 0:
            result.append(line[index])
            index += 1
            continue

        label = line[index + 1 : label_cursor]
        result.append(f"[[{markdown_link_target(''.join(destination))}][{label}]]")
        index = cursor + 1

    return "".join(result)


def convert_reference_links(line: str, references: dict[str, str]) -> str:
    def replace(match: re.Match[str]) -> str:
        label = match.group(1)
        reference = match.group(2)
        target = references.get(normalize_reference_label(reference))
        if not target:
            return match.group(0)
        return f"[[{target}][{label}]]"

    line = re.sub(r"(?<!!)\[([^\]\n]+)\]\[([^\]\n]+)\]", replace, line)
    line, explicit_links = protect_spans(line, r"\[\[.*?\]\]")

    def replace_collapsed(match: re.Match[str]) -> str:
        label = match.group(1)
        target = references.get(normalize_reference_label(label))
        if not target:
            return match.group(0)
        return f"[[{target}][{label}]]"

    line = re.sub(r"(?<!!)\[([^\]\n]+)\]\[\]", replace_collapsed, line)
    line, collapsed_links = protect_spans(line, r"\[\[.*?\]\]")
    line = re.sub(r"(?<!!)\[([^\]\n]+)\](?![\[(])", replace_collapsed, line)
    line = restore_spans(line, collapsed_links)
    return restore_spans(line, explicit_links)


def convert_markdown_links(line: str, references: dict[str, str]) -> str:
    line = convert_inline_markdown_links(line)
    line, org_links = protect_spans(line, r"\[\[.*?\]\]")
    line = convert_reference_links(line, references)
    line = re.sub(r"<([A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,})>", r"[[mailto:\1][\1]]", line)
    line = re.sub(r"<([A-Za-z][A-Za-z0-9+.-]*:[^>\s]+)>", r"[[\1]]", line)
    return restore_spans(line, org_links)


def convert_emphasis(line: str) -> str:
    converted: list[str] = []
    line = protect_converted_spans(line, r"\*\*\*([^*\n]+)\*\*\*", converted, r"*/\1/*")
    line = protect_converted_spans(line, r"___([^_\n]+)___", converted, r"*/\1/*")
    line = protect_converted_spans(line, r"\*\*([^*\n]*?)\*([^*\n]+)\*([^*\n]*?)\*\*", converted, r"*\1/\2/\3*")
    line = protect_converted_spans(line, r"\*([^*\n]*?)\*\*([^*\n]+)\*\*([^*\n]*?)\*", converted, r"/\1*\2*\3/")
    line = re.sub(r"(?<![\w*])\*([^*\n]+)\*(?![\w*])", r"/\1/", line)
    line = re.sub(r"(?<![\w_])_([^_\n]+)_(?![\w_])", r"/\1/", line)
    line = re.sub(r"\*\*([^*\n]+)\*\*", r"*\1*", line)
    line = re.sub(r"__([^_\n]+)__", r"*\1*", line)
    line = re.sub(r"<u>([^<\n]+)</u>", r"_\1_", line, flags=re.IGNORECASE)
    line = re.sub(r"~~([^~\n]+)~~", r"+\1+", line)
    line = re.sub(r"\+\+([^+\n]+)\+\+", r"+\1+", line)
    return restore_spans(line, converted)


def convert_inline_markup(
    line: str,
    lookup: dict[str, LedgerEntry | None],
    headings: dict[Path, set[str]],
    note: Note,
    output_root: Path,
    convert_wiki_links: bool,
) -> str:
    line, images = protect_spans(line, r"!\[[^\]\n]*\]\([^)\n]+\)")
    line, code = protect_spans(line, r"`{1,2}[^`\n]+`{1,2}")
    if convert_wiki_links:
        line = convert_wikilinks(line, lookup, headings, note, output_root)
    line = convert_markdown_links(line, note.references)
    line, links = protect_spans(line, r"!\[\[.*?\]\]|\[\[.*?\]\]")
    line = convert_emphasis(line)
    line = restore_spans(line, links)
    line = restore_spans(line, code)
    line = convert_inline_code(line)
    return restore_spans(line, images)


def convert_headline_text(
    line: str,
    lookup: dict[str, LedgerEntry | None],
    headings: dict[Path, set[str]],
    note: Note,
    output_root: Path,
    convert_wiki_links: bool,
) -> str:
    tags = inline_tags_outside_links(line)
    converted = convert_inline_markup(strip_inline_tags(line), lookup, headings, note, output_root, convert_wiki_links)
    normalized = [normalize_tag(tag) for tag in tags]
    normalized = [tag for tag in normalized if tag]
    if not normalized:
        return converted
    return f"{converted.rstrip()} :{':'.join(normalized)}:"


def markdown_indent_level(indent: str, parent_level: int) -> int:
    if not indent:
        return parent_level + 1
    return parent_level + len(indent.expandtabs(2)) // 2 + 1


def is_table_separator(line: str) -> bool:
    return re.match(r"^\s*\|?\s*:?-{3,}:?\s*(\|\s*:?-{3,}:?\s*)+\|?\s*$", line) is not None


def is_thematic_break(line: str) -> bool:
    return re.match(r"^\s*(?:-{3,}|\*{3,}|_{3,})\s*$", line) is not None


def normalize_table_line(line: str) -> str:
    stripped = line.strip()
    if not stripped.startswith("|"):
        stripped = "| " + stripped
    if not stripped.endswith("|"):
        stripped = stripped + " |"
    cells = [cell.strip() for cell in stripped.strip("|").split("|")]
    return "| " + " | ".join(cells) + " |"


def normalize_table_separator(line: str) -> str:
    stripped = line.strip()
    if not stripped.startswith("|"):
        stripped = "| " + stripped
    if not stripped.endswith("|"):
        stripped = stripped + " |"
    cells = [cell.strip() for cell in stripped.strip("|").split("|")]
    return "|" + "+".join("---" for _ in cells) + "|"


def table_cells(line: str) -> list[str]:
    return [cell.strip() for cell in line.strip().strip("|").split("|")]


def is_org_table_line(line: str) -> bool:
    return line.strip().startswith("|")


def is_org_table_hline(line: str) -> bool:
    return re.match(r"^\s*\|[-+]+\|\s*$", line) is not None


def format_org_table(rows: list[str]) -> list[str]:
    parsed_rows = [None if is_org_table_hline(row) else table_cells(row) for row in rows]
    column_count = max((len(row) for row in parsed_rows if row), default=0)
    widths = [1] * column_count

    for row in parsed_rows:
        if not row:
            continue
        for index, cell in enumerate(row):
            widths[index] = max(widths[index], len(cell))

    formatted: list[str] = []
    for row in parsed_rows:
        if row is None:
            formatted.append("|" + "+".join("-" * (width + 2) for width in widths) + "|")
            continue
        padded = [cell.ljust(widths[index]) for index, cell in enumerate(row)]
        padded.extend(" " * width for width in widths[len(padded) :])
        formatted.append("| " + " | ".join(padded) + " |")
    return formatted


def format_org_tables(lines: list[str]) -> list[str]:
    formatted: list[str] = []
    index = 0
    while index < len(lines):
        if not is_org_table_line(lines[index]):
            formatted.append(lines[index])
            index += 1
            continue

        start = index
        while index < len(lines) and is_org_table_line(lines[index]):
            index += 1
        formatted.extend(format_org_table(lines[start:index]))

    return formatted


def convert_body(
    body: str,
    lookup: dict[str, LedgerEntry | None],
    headings: dict[Path, set[str]],
    targeted_headings: dict[Path, set[str]],
    note: Note,
    output_root: Path,
    convert_wiki_links: bool,
) -> list[str]:
    output: list[str] = []
    in_src = False
    callout_kind: str | None = None
    heading_ids: dict[str, str] = {}
    current_heading_level = 0

    for line in body.splitlines():
        fence = re.match(r"^(```|~~~)(.*)$", line)
        if fence:
            if in_src:
                output.append("#+end_src")
                in_src = False
            else:
                language = fence.group(2).strip() or "text"
                output.append(f"#+begin_src {language}")
                in_src = True
            continue

        if in_src:
            output.append(line)
            continue

        if re.match(r"^\[[^\]]+\]:\s+\S+", line):
            continue

        if is_thematic_break(line):
            continue

        callout = re.match(r"^>\s*\[!(\w+)\]\s*(.*)$", line)
        if callout:
            if callout_kind:
                output.append("#+end_callout")
            callout_kind = callout.group(1).lower()
            title = convert_inline_markup(callout.group(2).strip(), lookup, headings, note, output_root, convert_wiki_links)
            output.append(f"#+begin_callout {callout_kind} {title}".rstrip())
            continue

        if callout_kind and line.startswith(">") and not re.match(r"^>\s*\[!(\w+)\]", line):
            output.append(line[1:].lstrip())
            continue

        if callout_kind and not line.startswith(">"):
            output.append("#+end_callout")
            callout_kind = None

        heading = re.match(r"^(#{1,6})\s+(.+?)\s*$", line)
        if heading:
            title = convert_headline_text(heading.group(2).strip(), lookup, headings, note, output_root, convert_wiki_links)
            stars = "*" * len(heading.group(1))
            current_heading_level = len(heading.group(1))
            output.append(f"{stars} {title}")
            clean_title = clean_heading_title(heading.group(2))
            if clean_title in targeted_headings.get(note.relative, set()) and clean_title not in heading_ids:
                heading_ids[clean_title] = heading_custom_id(note.relative, clean_title)
                output.append(":PROPERTIES:")
                output.append(f":CUSTOM_ID: {heading_ids[clean_title]}")
                output.append(":END:")
            continue

        checkbox = re.match(r"^(\s*)[-*+]\s+\[([ xX!?>~])\]\s*(.*)$", line)
        if checkbox:
            indent = checkbox.group(1)
            state = CHECKBOX_TODOS.get(checkbox.group(2), "TODO")
            text = convert_headline_text(checkbox.group(3), lookup, headings, note, output_root, convert_wiki_links)
            level = max(1, markdown_indent_level(indent, current_heading_level))
            output.append(f"{'*' * level} {state} {text}".rstrip())
            continue

        bullet = re.match(r"^(\s*)[-*+]\s+(.*)$", line)
        if bullet:
            output.append(
                f"{bullet.group(1)}+ {convert_inline_markup(bullet.group(2), lookup, headings, note, output_root, convert_wiki_links)}"
            )
            continue

        if is_table_separator(line):
            output.append(normalize_table_separator(line))
            continue

        if "|" in line and line.strip().startswith("|"):
            output.append(normalize_table_line(convert_inline_markup(line, lookup, headings, note, output_root, convert_wiki_links)))
            continue

        output.append(convert_inline_markup(line, lookup, headings, note, output_root, convert_wiki_links))

    if in_src:
        output.append("#+end_src")
    if callout_kind:
        output.append("#+end_callout")

    return format_org_tables(output)


def render_note(
    note: Note,
    lookup: dict[str, LedgerEntry | None],
    headings: dict[Path, set[str]],
    targeted_headings: dict[Path, set[str]],
    output_root: Path,
    convert_wiki_links: bool,
) -> str:
    aliases = parse_list(note.frontmatter.get("aliases", []))
    tags = parse_list(note.frontmatter.get("tags", []))

    lines = [
        ":PROPERTIES:",
        f":ID: {note.org_id}",
    ]
    for field in ("created", "updated"):
        value = note.frontmatter.get(field)
        if isinstance(value, str) and value.strip():
            lines.append(f":{field.upper()}: {value.strip()}")
    lines.extend([
        ":END:",
        f"#+title: {note.title}",
    ])

    if aliases:
        lines.append("#+ROAM_ALIASES: " + " ".join(f'"{alias}"' for alias in aliases))

    tags_line = org_filetags(tags)
    if tags_line:
        lines.append(tags_line)

    lines.append("")
    lines.extend(convert_body(note.body, lookup, headings, targeted_headings, note, output_root, convert_wiki_links))
    return "\n".join(lines).rstrip() + "\n"


def unresolved_wikilinks(note: Note, output: Path, lookup: dict[str, LedgerEntry | None], headings: dict[Path, set[str]]) -> list[LinkIssue]:
    unresolved: list[LinkIssue] = []
    in_src = False
    for line_number, line in enumerate(note.target.read_text(encoding="utf-8").splitlines(), 1):
        if line.startswith("#+begin_src"):
            in_src = True
            continue
        if line.startswith("#+end_src"):
            in_src = False
            continue
        if in_src:
            continue
        inline_code_spans = [match.span() for match in re.finditer(r"~[^~\n]+~", line)]
        for match in re.finditer(r"(?<!!)\[\[([^\]\n]+)\]\]", line):
            if in_spans(match.start(), inline_code_spans):
                continue
            target, heading, _ = split_wikilink(match.group(1))
            if target.startswith(("id:", "file:", "#")) or re.match(r"^[A-Za-z][A-Za-z0-9+.-]*:", target):
                continue
            resolved = note_ledger_entry(note, output) if heading and not target else lookup.get(target.lower()) or lookup.get(lookup_key(target))
            if heading and resolved and clean_heading_title(heading) not in headings.get(resolved.source, set()):
                reason = "missing heading"
            elif target.lower() in lookup and lookup[target.lower()] is None:
                reason = "ambiguous target"
            elif lookup_key(target) in lookup and lookup[lookup_key(target)] is None:
                reason = "ambiguous target"
            else:
                reason = "missing target"
            unresolved.append(LinkIssue(note, line_number, line, reason))

        markdown_scan_line = re.sub(r"\[\[.*?\]\]", "", line)
        for match in re.finditer(r"(?<!!)\[([^\]\n]+)\]\[([^\]\n]*)\]", markdown_scan_line):
            missing_key = match.group(2) or match.group(1)
            unresolved.append(LinkIssue(note, line_number, line, f"missing reference: {missing_key}"))
    return unresolved


def escape_table_cell(value: object) -> str:
    return str(value).replace("\n", "<br>").replace("|", "&#124;")


def unescape_table_cell(value: str) -> str:
    return value.strip().replace("&#124;", "|").replace("<br>", "\n")


def split_ledger_row(line: str) -> list[str]:
    return [unescape_table_cell(cell) for cell in line.strip().strip("|").split("|")]


def read_ledger_entries(output: Path) -> list[LedgerEntry]:
    ledger = output / "conversion-ledger.md"
    entries: list[LedgerEntry] = []
    for line in ledger.read_text(encoding="utf-8").splitlines():
        if not line.startswith("| ") or line.startswith("| ---") or line.startswith("| Source "):
            continue
        cells = split_ledger_row(line)
        if len(cells) < 5:
            continue
        entries.append(
            LedgerEntry(
                Path(cells[0]),
                Path(cells[1]),
                cells[2],
                cells[3],
                [alias for alias in cells[4].split(", ") if alias],
            )
        )
    return entries


def write_ledger(
    notes: list[Note],
    output: Path,
    lookup: dict[str, LedgerEntry | None],
    headings: dict[Path, set[str]],
    collisions: dict[str, list[LedgerEntry]],
    include_unresolved: bool,
) -> None:
    lines = [
        "# Org Conversion Ledger",
        "",
        "| Source | Target | Title | Org ID | Aliases |",
        "| --- | --- | --- | --- | --- |",
    ]
    for note in notes:
        aliases = ", ".join(parse_list(note.frontmatter.get("aliases", [])))
        row = [
            note.relative.as_posix(),
            note.target.relative_to(output).as_posix(),
            note.title,
            note.org_id,
            aliases,
        ]
        lines.append("| " + " | ".join(escape_table_cell(cell) for cell in row) + " |")

    lines.extend(["", "## Duplicate Link Keys", ""])
    if collisions:
        lines.extend([
            "| Lookup Key | Sources |",
            "| --- | --- |",
        ])
        for key, duplicate_entries in sorted(collisions.items()):
            sources = ", ".join(entry.source.as_posix() for entry in duplicate_entries)
            lines.append(f"| {escape_table_cell(key)} | {escape_table_cell(sources)} |")
    else:
        lines.append("- None")

    warnings = [ConversionWarning(note, "malformed frontmatter") for note in notes if note.malformed_frontmatter]
    lines.extend(["", "## Conversion Warnings", ""])
    if warnings:
        for warning in warnings:
            target = warning.note.target.relative_to(output).as_posix()
            lines.append(f"- `{target}` [{warning.reason}]")
    else:
        lines.append("- None")

    if include_unresolved:
        unresolved: list[LinkIssue] = []
        for note in notes:
            unresolved.extend(unresolved_wikilinks(note, output, lookup, headings))

        lines.extend(["", "## Unresolved Wikilinks", ""])
        if unresolved:
            for issue in unresolved:
                target = issue.note.target.relative_to(output).as_posix()
                lines.append(f"- `{target}:{issue.line_number}` [{issue.reason}] {issue.text}")
        else:
            lines.append("- None")
    else:
        lines.extend(["", "## Unresolved Wikilinks", "", "- Pending second-pass link rewrite"])

    (output / "conversion-ledger.md").write_text("\n".join(lines) + "\n", encoding="utf-8")


def ensure_safe_output(vault: Path, output: Path) -> None:
    protected_trees = [vault, Path("/home/seth/org").resolve()]
    for path in protected_trees:
        if output == path or output in path.parents or path in output.parents:
            raise SystemExit(f"refusing unsafe output path: {output}")

    if output in {Path.home().resolve(), Path("/")}:
        raise SystemExit(f"refusing unsafe output path: {output}")


def is_marked_conversion_output(output: Path) -> bool:
    marker = output / CONVERSION_MARKER
    return marker.is_file() and marker.read_text(encoding="utf-8") == CONVERSION_MARKER_TEXT


def convert(vault: Path, output: Path, force: bool) -> None:
    ensure_safe_output(vault, output)
    if output.exists():
        if not force:
            raise SystemExit(f"{output} already exists; pass --force to replace it")
        if output != DEFAULT_OUTPUT.resolve():
            raise SystemExit(f"--force only replaces the default generated output: {DEFAULT_OUTPUT}")
        if not is_marked_conversion_output(output):
            raise SystemExit(f"refusing to replace unmarked output path: {output}")
        shutil.rmtree(output)

    output.mkdir(parents=True)
    notes = collect_notes(vault, output)
    lookup, collisions = build_lookup(notes, output)
    headings = build_heading_index(notes)
    empty_targeted_headings = {note.relative: set() for note in notes}

    for note in notes:
        note.target.parent.mkdir(parents=True, exist_ok=True)
        note.target.write_text(render_note(note, {}, headings, empty_targeted_headings, output, convert_wiki_links=False), encoding="utf-8")

    (output / CONVERSION_MARKER).write_text(CONVERSION_MARKER_TEXT, encoding="utf-8")
    write_ledger(notes, output, lookup, headings, collisions, include_unresolved=False)

    ledger_lookup, ledger_collisions = build_lookup_entries(read_ledger_entries(output))
    targeted_headings = targeted_heading_index(notes, ledger_lookup, headings)
    for note in notes:
        note.target.write_text(render_note(note, ledger_lookup, headings, targeted_headings, output, convert_wiki_links=True), encoding="utf-8")

    write_ledger(notes, output, ledger_lookup, headings, ledger_collisions, include_unresolved=True)
    print(f"converted {len(notes)} notes into {output}")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--vault", type=Path, default=DEFAULT_VAULT)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--force", action="store_true")
    args = parser.parse_args()

    convert(args.vault.expanduser().resolve(), args.output.expanduser().resolve(), args.force)


if __name__ == "__main__":
    main()
