[colors.primary]
background = "#32302f"
foreground = "#d5c4a1"
dim_foreground = "#665c54"
bright_foreground = "#fbf1c7"

[colors.cursor]
text = "#32302f"
cursor = "#d5c4a1"

[colors.vi_mode_cursor]
text = "#32302f"
cursor = "#d5c4a1"

[colors.search.matches]
foreground = "#32302f"
background = "#83a598"

[colors.search.focused_match]
foreground = "#32302f"
background = "#fabd2f"

[colors.footer_bar]
foreground = "#d5c4a1"
background = "#32302f"

[colors.hints.start]
foreground = "#32302f"
background = "#fabd2f"

[colors.hints.end]
foreground = "#d5c4a1"
background = "#32302f"

[colors.selection]
text = "#d5c4a1"
background = "#665c54"

[colors.normal]
black = "#32302f"
red = "#fb4934"
green = "#b8bb26"
yellow = "#fabd2f"
blue = "#83a598"
magenta = "#d3869b"
cyan = "#8ec07c"
white = "#d5c4a1"

[colors.bright]
black = "#665c54"
red = "#fb4934"
green = "#b8bb26"
yellow = "#fabd2f"
blue = "#83a598"
magenta = "#d3869b"
cyan = "#8ec07c"
white = "#fbf1c7"

[colors.dim]
black = "#665c54"
red = "#fb4934"
green = "#b8bb26"
yellow = "#fabd2f"
blue = "#83a598"
magenta = "#d3869b"
cyan = "#8ec07c"
white = "#fbf1c7"

[[colors.indexed_colors]]
index = 16
color = "#fabd2f"

[[colors.indexed_colors]]
index = 17
color = "#fb4934"
